name = "tidb-prisma-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-03-04"
node_compat = true

[vars]
DATABASE_URL = "mysql://2Q6osJ8qKC7ybg7.root:tpD52GEqezAlVvnd@gateway01.us-east-1.prod.aws.tidbcloud.com:4000/test03?sslaccept=strict"